### ISSUE TITLE
Facebook Ads not showing 

### ISSUE THREAD

**Issue by eyeveye** [eduardoqc183/XamarinFormsFacebookAdsDemo#2]
I have tested my app loaded with the plugin, include published on PlayStore. The FB Ads is not showing.

I tested with your application too, it is also not showing.

Note: I have my facebook installed and logged in.

**Comment by eduardoqc183** [comment]
If is the first time implementing fb ads in playstore you must use bidding, fb is not working with cascade ads anymore since this year. I had to implement bidding to have ads in my app also.
more info [here](https://www.facebook.com/audiencenetwork/resources/blog/audience-network-to-become-bidding-only-beginning-with-ios-in-2021)

**Comment by eyeveye** [comment]
> If is the first time implementing fb ads in playstore you must use bidding, fb is not working with cascade ads anymore since this year. I had to implement bidding to have ads in my app also.
> more info [here](https://www.facebook.com/audiencenetwork/resources/blog/audience-network-to-become-bidding-only-beginning-with-ios-in-2021)

Gosh, thanks for this information! So I just have to rely on AdMob (which is terribly bad) to get the bidding.

Thanks Again.
